#+title: Buraiyen's Doom Emacs Config
#+AUTHOR: Brian Nguyen (Buraiyen)
#+PROPERTY: header-args :tangle config.el
#+auto_tangle: t
#+STARTUP: showeverything

* TABLE OF CONTENTS :toc:
- [[#about-this-config--doom-emacs][ABOUT THIS CONFIG / DOOM EMACS]]
- [[#emacs-client--emacs-daemon][EMACS CLIENT / EMACS DAEMON]]
- [[#general-configs][GENERAL CONFIGS]]
  - [[#full-name--email][Full Name / Email]]
  - [[#general-keybindings][General Keybindings]]
  - [[#line-numbers][Line Numbers]]
  - [[#open-specific-files][Open Specific Files]]
  - [[#looks][Looks]]
- [[#beacon][BEACON]]
- [[#calendar][CALENDAR]]
- [[#centaur-tabs][CENTAUR TABS]]
- [[#dashboard][DASHBOARD]]
- [[#emmet-mode][EMMET MODE]]
- [[#org-mode][ORG MODE]]
  - [[#basic-setup][Basic Setup]]
  - [[#org-roam][Org Roam]]
  - [[#org-roam-ui][Org Roam UI]]
  - [[#org-auto-tangle][Org Auto Tangle]]
- [[#neotree][NEOTREE]]
- [[#rainbow-mode][RAINBOW MODE]]

* ABOUT THIS CONFIG / DOOM EMACS
Doom Emacs is a configuration framework for GNU Emacs. It uses the "evil"
keybindings set to emulate Vim keybindings. Doom Emacs has various different
packages and customization for you to choose. Below is my custom configuration
of it, and feel free to use / modify whatever you like

[[https://github.com/doomemacs/][Link to Doom Emacs GitHub project]]

* EMACS CLIENT / EMACS DAEMON
Doom Emacs is optimized for speed. The appropriate way to launch Doom Emacs is to set up an Emacs daemon

~/usr/bin/emacs --daemon~

Then to start emacsclient, you would run this command

~emacsclient -c -a 'emacs'~

This will launch emacs a lot quicker than if you were to do it just by using the regular ~emacs~ command. The ~-a~ flag ensures that in case emacsclient fails to launch, then Emacs would launch instead

* GENERAL CONFIGS
The configs in this section are not related to any third-pary packages

** Full Name / Email

Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets. If you don't use any of these services, then
you don't have to fill out these fields

#+begin_src emacs-lisp
(setq user-full-name "Brian Nguyen"
      user-mail-address "brian.edison.nguyen@gmail.com")
#+end_src

** General Keybindings
In default Vim, navigating up and down around a word wrap would just jump to the
first or last character. The bindings below makes it so that navigating though a
word wrap would go through each line

As always, if you want to separate text bodies into different lines, you could use ~gq~

#+begin_src emacs-lisp
(define-key evil-normal-state-map (kbd "j") 'evil-next-visual-line)
(define-key evil-normal-state-map (kbd "k") 'evil-previous-visual-line)
#+end_src

** Line Numbers
Line numbers are currently set to relative. Using ~'nil~ removes line numbers

#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src

** Open Specific Files
These are keybindings to open files that I commonly use

| PATH TO FILE                   | DESCRIPTION              | KEYBINDING |
|--------------------------------+--------------------------+------------|
| ~/.doom.d/config.org           | /Edit doom config.org/   | SPC = c  |
| ~/.doom.d/init.el              | /Edit doom init.el/      | SPC = i  |
| ~/.doom.d/packages.el          | /Edit doom packages.org/ | SPC = p  |
| ~/Documents/journal/agenda.org | /Edit agenda file/       | SPC = a  |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("=" . "open file")
       :desc "Edit doom config.org" "c" #'(lambda () (interactive) (find-file "~/.doom.d/config.org"))
       :desc "Edit doom init.el" "i" #'(lambda () (interactive) (find-file "~/.doom.d/init.el"))
       :desc "Edit doom packages.el" "p" #'(lambda () (interactive) (find-file "~/.doom.d/packages.el"))
       :desc "Edit agenda.org" "a" #'(lambda () (interactive) (find-file "~/Documents/notes/agenda.org"))
))
#+end_src

** Looks
*** Font
Doom exposes five (optional) variables for controlling fonts in Doom.

| Font Type                  | Description                                                  |
|----------------------------+--------------------------------------------------------------|
| `doom-font'                | Your standard font                                           |
| `doom-variable-pitch-font' | For some Emacs applications                                  |
| `doom-big-font'            | For `doom-big-font-mode' ~SPC t b~                           |
| `font-lock-comment-face'   | For comments                                                 |
| `font-lock-keyword-face'   | For keywords with special significance, like `setq` in elips |


#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMonoMedium Nerd Font Mono" :size 15)
      doom-variable-pitch-font (font-spec :family "Ubuntu" :size 15))

#+end_src

*** Theme
Set the theme for Doom Emacs. The 'enable' commands seem to not work for me. Would need to find out why

#+begin_src emacs-lisp
(use-package doom-themes
  :ensure t
  :config
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t)
  :init
  (load-theme 'doom-one t))
(custom-set-faces!
  '(font-lock-comment-face :slant italic)
  '(font-lock-keyword-face :slant italic))

#+end_src

*** Window Size
The setting below sets Emacs to open maximized without it being fully
fullscreen. For some reason this works well on my main machine but not my
laptop. I'll have to look into it

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

*** Window Transparency
The transparency is set to 90%. It looks great if you are using window blur with a compositor

#+begin_src emacs-lisp
(if (daemonp)
    (add-hook 'after-make-frame-functions
        (lambda (frame)
            (select-frame frame)
            (set-frame-parameter (selected-frame) 'alpha '(90 90)))
   (set-frame-parameter (selected-frame) 'alpha '(90 90))))
#+end_src



* BEACON
Beacon is a very useful tool for locating your cursor. Whenever you scroll, a flashing light flashes horizontally on your cursor

#+begin_src emacs-lisp
(beacon-mode 1)
(setq beacon-blink-when-point-moves-vertically 1
      beacon-color "#F28AB3" ;; light pink color
      beacon-blink-when-buffer-changes t
      beacon-blink-when-window-scrolls t)
#+end_src

* CALENDAR
Opens up a full graphical 12-month calendar with agendas and holidays listed.

#+begin_src emacs-lisp
(global-set-key (kbd "C-c c") '=calendar)

(setq holiday-general-holidays nil
      holiday-christian-holidays nil
      holiday-hebrew-holidays nil
      holiday-islamic-holidays nil
      holiday-bahai-holidays nil
      holiday-oriental-holidays nil)
#+end_src

* CENTAUR TABS
Centaur tabs is part of the modern IDE look where different buffers are separated into tabs at the top of the screen

#+begin_src emacs-lisp
;; needed to work in emacsclient
(require 'centaur-tabs)
(setq centaur-tabs-set-bar 'over
      centaur-tabs-set-icons t
      centaur-tabs-gray-out-icons 'buffer
      centaur-tabs-height 24
      centaur-tabs-set-modified-marker t
      centaur-tabs-style "bar"
      centaur-tabs-modified-marker "•")

#+end_src

* DASHBOARD
A customizable startup screen when launching Emacs.

#+begin_src emacs-lisp
(use-package dashboard
  :ensure t
  :config
  (dashboard-setup-startup-hook))
(after! dashboard
  (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*"))
   dashboard-banner-logo-title "\nKEYBINDINGS\
                                 \nFind file          (SPC .)\
                                 \nEdit Doom Config   (SPC = c)\
                                 \nEdit Doom Init     (SPC = i)\
                                 \nEdit Doom Packages (SPC = p)\
                                 \nEdit agenda        (SPC = a)"
   dashboard-startup-banner "~/.doom.d/doom-emacs-dash.png"
   dashboard-set-heading-icons t
   dashboard-set-file-icons t
   dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 5)
                          (projects . 5)
                          (registers . 5))))

#+end_src

* EMMET MODE
Emmet is a plugin that improves HTML and CSS workflow

#+begin_src emacs-lisp
(use-package emmet-mode
  :ensure t
  :config
  (add-to-list 'emmet-jsx-major-modes 'jsx-mode))

(map! :leader
      :desc "Toggle emmet mode"
      "e m" #'emmet-mode)
#+end_src

* ORG MODE
Org mode is a markdown mode for note-taking, writing journals, planning agendas,
etc. This is the main reason why I'm using Doom Emacs, and it has been an
enjoyable experience for me

https://orgmode.org/

** Basic Setup
Included in this setup are org-agenda and org-journal
#+begin_src emacs-lisp
(after! org
  (setq org-agenda-files '("~/Documents/notes/agenda.org")
      org-journal-dir "~/Documents/notes/journal/"
      org-journal-file-header "#+TITLE: %M %Y"
      org-journal-date-format "%A, %Y-%m-%d"
      org-journal-file-type 'monthly
      org-journal-file-format "%Y-%m.org"
      org-superstar-headline-bullets-list '("◉" "●" "○" "◆" "●" "○" "◆")
      )
  ;; Needed to fix tabbing on headers
  (setq org-fold-core-style 'overlays)
)

#+end_src

** Org Roam
Org roam is an efficient way of note-taking. Creating a org file creates a node, and you can
link nodes together, forming a chain of relevant documents

#+begin_src emacs-lisp
(after! org
  (setq org-roam-directory "~/Documents/notes/"))
#+end_src

** Org Roam UI
org-roam-ui is a beautiful frontend for your org-roam

#+begin_src emacs-lisp
(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))

(map! :leader
      :desc "Toggle org-roam-ui-mode"
      "n r u" #'org-roam-ui-mode)
#+end_src

** Org Auto Tangle
Org auto tangle is used for taking block code inside org documents and transferring them to other files. I mainly use this to write these config documents

#+begin_src emacs-lisp
(use-package! org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode)
  :config
  (setq org-auto-tangle-default t))
#+end_src

* NEOTREE
Neotree displays the list of files in your current project, just like VS Code or any IDE

| COMMAND      | DESCRIPTION                                     | KEYBINDING |
|--------------+-------------------------------------------------+------------|
| neotree/open | Displays neotree on the left side of the window | ~SPC o p~  |

#+begin_src emacs-lisp
(require 'neotree)
(with-eval-after-load 'doom-themes
  (doom-themes-neotree-config)
  (setq doom-themes-neotree-file-icons t)
 )
#+end_src

* RAINBOW MODE
Rainbow mode displays the actual color for any hex value. The following enables
global rainbow mode (except org agenda since rainbow-mode destroys all
highlighting)

#+begin_src emacs-lisp
(define-globalized-minor-mode global-rainbow-mode rainbow-mode
  (lambda ()
    (when (not (memq major-mode
                (list 'org-agenda-mode)))
     (rainbow-mode 1))))
(global-rainbow-mode 1 )
#+end_src

